### ISSUE TITLE
Question: Is delay per IP or for all IPs?

### ISSUE THREAD

**Issue by Creative-Difficulty** [nfriedly/express-slow-down#25]
I want the delay to be for each IP accessing the JSON API separately.
For example: 
Client 1 --> Server (100 Requests in under 1 Minute)
Client 2 --> Server (less than 100 Requests in under 1 Minute)

Is the slow down for all Clients or only for Client 1?
(I have already configured `slowDown` to match my little Demo above:

```js
const speedLimiter = slowDown({
    windowMs: 1 * 60 * 1000, // 1 minute
    delayAfter: 100, // allow 100 requests per minute, then...
    delayMs: 500 // add delay to every request after 100 requests in 1 minute
});

```

Thanks for any answers,
Alex

**Comment by Creative-Difficulty** [comment]
Bump

**Comment by nfriedly** [comment]
It's per IP. 

However, if you have a load balancer or other proxy between your server and the clients, then you must set express's `trust proxy` setting appropriately, or else it will rate-limit the proxy's IP instead of the end-user's - see http://expressjs.com/en/guide/behind-proxies.html
