### ISSUE TITLE
maxDelayMs missing from @types/express-slow-down

### ISSUE THREAD

**Issue by mikamoush** [nfriedly/express-slow-down#8]
Hello,

I m using @types/express-slow-down for my typescript expressjs project. And I noticed that the option maxDelayMs is missing in the typescript adapter. It's a shame because without this option, the delay applied to my requests keeps increasing. Is this on purpose ?

Thanks

**Comment by nfriedly** [comment]
Fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41995
